### PR TITLE
Fix type annotations in docs.

### PR DESCRIPTION
**Pull request by kfollesdal**
Fix wrong type annotations for example of Namespace strict mode.

### CODE REVIEW

**Comment by seandstewart** [comment]
hey @kfollesdal - 

Thanks for submitting this PR - however according to [MyPy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#when-you-re-puzzled-or-when-things-are-complicated), the `*args: str` is the appropriate annotation. Can you tell me what static type-checker was raising the error for you?

**Comment by kfollesdal** [comment]
Discovered Typical today, looks really promising. 

When I try add(1,2) with def from docs. I get the following error: 
``
---------------------------------------------------------------------------
ConstraintValueError                      Traceback (most recent call last)
<ipython-input-3-0eb3bf25c4aa> in <module>
----> 1 typ.add(1,2)

~\Desktop\tmp\typ\.venv\Lib\site-packages\typic\api.py in func_wrapper(*args, **kwargs)
    153     @functools.wraps(func)
    154     def func_wrapper(*args, **kwargs) -> _T:
--> 155         bound = bind(func, *args, strict=strict, **kwargs)
    156         return bound.eval()
    157

~\Desktop\tmp\typ\.venv\Lib\site-packages\typic\serde\binder.py in bind(self, obj, partial, coerce, strict, *args, **kwargs)
    324         typic.constraints.error.ConstraintValueError: Given value <3.0> fails constraints: (type=int, nullable=False, coerce=False)
    325         """
--> 326         return self._bind_input(
    327             obj=obj,
    328             annos=self.resolver.protocols(obj, strict=strict)

~\Desktop\tmp\typ\.venv\Lib\site-packages\typic\serde\binder.py in _bind_input(self, obj, annos, params, args, kwargs, partial)
    255         parameters = deque(params.values())
    256         # Bind any positional arguments.
--> 257         posargs = self._bind_posargs(arguments, parameters, annos, args, kwargs)
    258         # Bind any keyword arguments.
    259         kwdargs = self._bind_kwdargs(arguments, parameters, annos, kwargs, partial)

~\Desktop\tmp\typ\.venv\Lib\site-packages\typic\serde\binder.py in _bind_posargs(self, arguments, params, annos, args, kwargs)
    133                 args = deque()
    134                 if anno:
--> 135                     value = anno(value)
    136                 argumentsset(name, value)
    137                 posargsadd(name)

~\Desktop\tmp\typ\.venv\Lib\site-packages\typic\serde\common.py in __call__(self, val)
    179
    180     def __call__(self, val: Any) -> ObjectT:
--> 181         return self.transmute(val)
    182
    183

~\Desktop\tmp\typ\.venv\Lib\site-packages\typic\constraints\common.py in validate(self, value, field)
    101         if not valid:
    102             field = f"{field}:" if field else "Given"
--> 103             raise ConstraintValueError(
    104                 f"{field} value <{value!r}> fails constraints: {self}"
    105             ) from None

ConstraintValueError: Given value <(1, 2)> fails constraints: (type=int, nullable=False, coerce=False)
``

**Comment by kfollesdal** [comment]
type of *num is a `tuple `and not `int` and then constraint check fails.

**Comment by kfollesdal** [comment]
Typical: 2.0.0b21
Python: 3.8.1

**Comment by seandstewart** [comment]
Ah, I see. This is a mistake in my own validator. It should detect varargs and handle each arg in turn.

**Comment by seandstewart** [comment]
Thanks for identifying this issue @kfollesdal. I’m closing this PR in favor of Issue #45.

**Pull request closed without merging**
