### PR TITLE
Schema generation: Name objects after their type rather the field nam…

### PR DESCRIPTION
**Pull request by syastrov**
…e where they were referenced

This helps to allow definitions to be reused.

### CODE REVIEW

**Comment by seandstewart** [comment]
Awesome 👏 - just a nit, can you do a rebase onto v2.1 + force push instead of merging 2.1 in? Helps to keep the commit history clean.

**Comment by syastrov** [comment]
Done. BTW, I noticed when running tests that the expected output was different than before.
It seems that since there was an ellipsis on `second: Data = ...`, that typical outputs title 'OptionalData' and allows the field to be nullable. This seems wrong to me, as it wouldn't match the type declaration (`Data`), since it's not declared as `Optional`..

**Comment by syastrov** [comment]
I have made a workaround so fields with `= ...` are not output as nullable in the JSON schema. Not sure if there's a cleaner way to do it.

**Comment by seandstewart** [comment]
Yeah that change looks fine to me, since it's still not registered as a required field 👍

**Comment by seandstewart** [comment]
Thanks for this contribution @syastrov! It's officially merged 🚀

**Comment by syastrov** [comment]
Awesome :)

**Pull request merged**
